// Curated playlist per region — real YouTube video IDs (100% verified embeddable)

export type Track = {
  id: string;
  title: string;
  artist: string;
  year?: string;
};

export type Region = 'mumbai' | 'delhi' | 'chennai' | 'kolkata';

export const REGIONS: { id: Region; label: string }[] = [
  { id: 'mumbai', label: 'Mumbai' },
  { id: 'delhi',  label: 'Delhi'  },
  { id: 'chennai', label: 'Chennai' },
  { id: 'kolkata', label: 'Kolkata' },
];

export const playlist: Record<Region, Track[]> = {
  // ── MUMBAI ── Classic Bollywood & Golden Era (100 verified embeddable tracks)
  mumbai: [
    { id: '8VgEQ1CqYTw', title: 'Aisa Lagta Hai', artist: 'Sonu Nigam' },
    { id: 'z7q1bwWDSHU', title: 'AISA PEHLI BAAR HUA HAI', artist: 'Sonu Nigam' },
    { id: 'ojHWxuQ0YWs', title: 'Chand Sitare', artist: 'Kumar Sanu' },
    { id: 'A1wZUXY--4U', title: 'Dil Laga Liya Maine', artist: 'Nadeem Shravan' },
    { id: 'kuEj094GWQs', title: 'Kem Chhe', artist: 'Bali Brahmbhatt' },
    { id: 'MNliIHZfnA0', title: 'Yeh Tara Woh Tara', artist: 'Udit Narayan' },
    { id: 'xpuQCX_Jocg', title: 'TUMHE JO MAINE DEKHA', artist: 'Abhijeet' },
    { id: '9V2ys5u3a5Q', title: 'Chupke Se Sun', artist: 'Udit Narayan' },
    { id: 'hRInJW8ubYw', title: 'It\'s the Time to Disco', artist: 'Shankar Ehsaan Loy' },
    { id: '_xQuobKhasg', title: 'Maahi Ve', artist: 'Shankar Ehsaan Loy' },
    { id: 'yqtGt2IjyKg', title: 'Main Yahaan Hoon', artist: 'Udit Narayan' },
    { id: 'ZaURV4XxdPI', title: 'Chand Sifarish', artist: 'Shaan' },
    { id: 'bdS6OoH1W2A', title: 'Ajab Si', artist: 'Vishal - Shekhar' },
    { id: 'MzhsLzOTZNA', title: 'MAIN HOON NA', artist: 'Sonu Nigam' },
    { id: 'R0D7rRmbasg', title: 'I Am the Best', artist: 'Abhijeet' },
    { id: 'zV7pfxeh5dY', title: 'Such Keh Raha Hai', artist: 'Kay Kay' },
    { id: 'vTBbi3qIC0s', title: 'Yun Hi Chala Chal', artist: 'Udit Narayan' },
    { id: 'RC54XdPtQTo', title: 'Chhalka Chhalka Re', artist: 'Richa Sharma' },
    { id: 'lKtUvzlD9L8', title: 'Rang De Basanti', artist: 'A. R. Rahman' },
    { id: 'DSMneXn238o', title: 'Roobaroo', artist: 'A. R. Rahman' },
    { id: '0XynbuGx4FI', title: 'Shikayat Hai', artist: 'Roop Kumar Rathod' },
    { id: 'DybAYiAEl3c', title: 'Pretty Woman', artist: 'Shankar Ehsaan Loy' },
    { id: '9mNSqnYDpOk', title: 'Mere Humsafar', artist: 'Alka Yagnik' },
    { id: '_FWiJf2uuvM', title: 'Tanhayee', artist: 'Sonu Nigam' },
    { id: 'ZiJgkQLunUM', title: 'Dilko Tumse Pyar Hua', artist: 'Roop Kumar Rathod' },
    { id: 'AvNyfTsiqBg', title: 'OODHNI', artist: 'Udit Narayan' },
    { id: '-7shFTSqU1g', title: 'Jaane Kyon Log Pyar', artist: 'Udit Narayan' },
    { id: 'd_QDYIJSkB8', title: 'Ye Ishq Hai', artist: 'Shreya Ghoshal' },
    { id: 'L4oNkUQgsVg', title: 'Aankhen Bandh Karke', artist: 'Udit Narayan' },
    { id: 'YmNNudulXlc', title: 'DIL DE DIYA HAI', artist: 'Anand Raj Anand' },
    { id: '3E1NLVzDZ_Y', title: 'Tujh Mein Rab Dikhta Hai', artist: 'Roop Kumar Rathod' },
    { id: 'IWjbBSMsQJg', title: 'Zara Zara', artist: 'Bombay Jayashree' },
    { id: 'NIUQnGjOIL8', title: 'O Humdum Suniyo Re', artist: 'Kay Kay' },
    { id: 'mFjwkgfLF7I', title: 'Chupke Se', artist: 'Sadhana Sargam' },
    { id: 'WF75r0CuQSA', title: 'Panchhi Nadiyan Pawan Ke Jhonke', artist: 'Sonu Nigam' },
    { id: 'NayBRkm8YOg', title: 'O Piya', artist: 'Sukhwinder Singh' },
    { id: 'c6cHxi2eLQ4', title: 'Maa', artist: 'Shankar Mahadevan' },
    { id: '1njJoSMLDrg', title: 'Panchhi Nadiyan Pawan Ke Jhonke', artist: 'Sonu Nigam' },
    { id: 'Euv8CPsZcTU', title: 'AYE MERI ZINDAGI', artist: 'Udit Narayan' },
    { id: 'wYqsktWxWBw', title: 'Aur Kya', artist: 'Abhijeet' },
    { id: 'quEm4_4c-Jg', title: 'Kabhi Alvida Naa Kehna', artist: 'Shankar Ehsaan Loy' },
    { id: 'DRwVEqejzqE', title: 'SEENA PADA', artist: 'Shreya Ghoshal' },
    { id: 'Eun-ukNlQi8', title: 'WADA RAHA', artist: 'Arnab Chakraborty' },
    { id: 'szCjTxg2K1Y', title: 'Banke Tera Jogi', artist: 'Alka Yagnik' },
    { id: 'atXiJ93lM2k', title: 'EK GARAM CHAI KI PYALI', artist: 'Anu Malik' },
    { id: '3BsFE3WD0kA', title: 'Aye Udi Udi Udi', artist: 'Adnan Sami' },
    { id: 'wzOWggEF0No', title: 'Kaisi Hai Ye Rut', artist: 'Srinivas' },
    { id: 'rbP95NoHhvU', title: 'Kaho Naa Pyar Hai', artist: 'Udit Narayan' },
    { id: 'MOFPRs3LFrU', title: 'Chal Jhoothi', artist: 'Udit Narayan' },
    { id: 'm_ydflTttPk', title: 'Raat Ki Hatheli Par', artist: 'Udit Narayan' },
    { id: 'Lf54R6xIgKg', title: 'AISA JADOO', artist: 'Sunidhi Chauhan' },
    { id: '7SRoR4sLQAM', title: 'Saanwariya Saanwariya', artist: 'Alka Yagnik' },
    { id: 'Lrh3kJoGYX0', title: 'Na Tum Jano Na Hum', artist: 'Lucky Ali' },
    { id: 'WLZkB9O8XNA', title: 'JHALAK DIKHLA JA', artist: 'Himesh Reshammiya' },
    { id: 'rvnyVvSRAxs', title: 'Piyu Bole', artist: 'Sonu Nigam' },
    { id: 'q9a3HjLeSJM', title: 'Suraj Hua Maddham', artist: 'Sandesh Shandilya' },
    { id: 'GLR3VyQlO8E', title: 'CHORI CHORI CHORA CHORI', artist: 'Shaan' },
    { id: 'U8_MuWSnkCg', title: 'Taare Zameen Par', artist: 'Shankar Mahadevan' },
    { id: 'YW25SKnlEi0', title: 'AAJ KI RAAT', artist: 'Alisha Chinai' },
    { id: 'EkZGKGolYlI', title: 'Awaarapan Banjarapan', artist: 'Kay Kay' },
    { id: '-R9jQxuZbJk', title: 'Kuch To Hua Hai', artist: 'Shankar Ehsaan Loy' },
    { id: '7EbxUL9bar4', title: 'O SATHIYA', artist: 'Udit Narayan' },
    { id: '6IdzEmpH4dk', title: 'Where\'s the Party Tonight', artist: 'Shankar Ehsaan Loy' },
    { id: 'qYUVDThXXiw', title: 'Mauja Hi Mauja', artist: 'Mika Singh' },
    { id: 'D0U7kd6yNaA', title: 'O Rey Chhori', artist: 'A. R. Rahman' },
    { id: 'MgGMoAHcM18', title: 'Jab Kisiki Taraf Dil', artist: 'Jatin Lalit' },
    { id: 'W_fU0LNOR40', title: 'Deewana Hai Dekho', artist: 'Sandesh Shandilya' },
    { id: 'AsieVqOTRs0', title: 'Mitwa', artist: 'Shankar Ehsaan Loy' },
    { id: 'd9r4XZBhKk8', title: 'Mitwa', artist: 'A. R. Rahman' },
    { id: 'khlR5jM2ZrI', title: 'Dard - E - Disco', artist: 'Sukhwinder Singh' },
    { id: '1nrKhy0z6JI', title: 'Kal Ho Naa Ho', artist: 'Shankar Ehsaan Loy' },
    { id: 'o5AbH0bVovs', title: 'Phir Bhi Dil Hai Hindustani', artist: 'Udit Narayan' },
    { id: 'u4m-EPPXqM0', title: 'Ajnabi Mujhko Itna Bata', artist: 'Jatin Lalit' },
    { id: 'ELZYwzTPUw4', title: 'TUMSE MILKE DIL KA', artist: 'Sonu Nigam' },
    { id: 'uovUU6FiI4E', title: 'MAIN HOON DON', artist: 'Shaan' },
    { id: 'cH_9ZwTVnuI', title: 'Radha Kaise Na Jale', artist: 'A. R. Rahman' },
    { id: 'p4664nVBMxg', title: 'Saathiya', artist: 'Sonu Nigam' },
    { id: 'V9jCjA5BCV4', title: 'Jaadu Hai Nasha', artist: 'Shreya Ghoshal' },
    { id: 'I94fhjQ-U30', title: 'Tum Se Hi', artist: 'Mohit Chauhan' },
    { id: '1kF1gw8Ewjk', title: 'Chalo Tumko Lekar', artist: 'Shreya Ghoshal' },
    { id: 'QMSIPuKEvps', title: 'TERE NAAM', artist: 'Udit Narayan' },
    { id: 'Xz0fMH6ClKY', title: 'Soniyo', artist: 'Raju Singh' },
    { id: 'eWgKYsPl_k8', title: 'Nazar Aa Raha Hai', artist: 'Udit Narayan' },
    { id: '8PEqEh1lnNE', title: 'Main Agar Kahoon', artist: 'Vishal - Shekhar' },
    { id: '1EOv0KOGjLQ', title: 'CHALE JAISE HAWAIEN', artist: 'Kay Kay' },
    { id: 'sLva5MIY7ZY', title: 'Woh Ladki Hai Kahan', artist: 'Shaan' },
    { id: '9ZPY9ZopT0k', title: 'Jadu Hai Nasha Hai', artist: 'Shreya Ghoshal' },
    { id: 'ar_m3IbjS4c', title: 'TUMSE MILNA', artist: 'Udit Narayan' },
    { id: 'YYFxN8j0ixA', title: 'Bumbro', artist: 'Shankar Mahadevan' },
    { id: 'tlZO7G-D0mg', title: 'Jashn-E-Bahaaraa', artist: 'A. R. Rahman' },
    { id: 'kp00LrbcRd4', title: 'Aye Dil Laya Hai Bahaar', artist: 'Kavita Krishnamurthy' },
    { id: 'k9vAlmEnoF4', title: 'Masti Ki Paathshala', artist: 'A. R. Rahman' },
    { id: 'TWHdwAWhcfs', title: 'Khalbali', artist: 'A. R. Rahman' },
    { id: 'IE4gZ9smLkk', title: 'You Are My Soniya', artist: 'Sandesh Shandilya' },
    { id: 'dy4AykZGIWA', title: 'Rehnaa Hai Tere Dil Mein', artist: 'Sonu Nigam' },
    { id: '8m1E-RF3Yz4', title: 'Tere Liye', artist: 'Lata Mangeshkar' },
    { id: 'KayWQCbGirU', title: 'Dil Chahta Hai', artist: 'Shankar Mahadevan' },
    { id: 'OUhrP5XtU_4', title: 'Pyar Ki Kashti Mein', artist: 'Udit Narayan' },
    { id: 'pdZ7x_aaIqs', title: 'Mere Haath Mein', artist: 'Sonu Nigam' },
    { id: '2xkx2QNVMM4', title: 'Kahin Pyaar Na Ho Jaaye', artist: 'Alka Yagnik' },
  ],

  // ── DELHI ── Verified Playable Pool (61 tracks)
  delhi: [
    { id: 'otQmzlm-s7Q', title: 'Main Duniya Bhula Doonga', artist: 'Kumar Sanu', year: '1990' },
    { id: 'Dz1Ad3cdtQA', title: 'Ek Aisi Ladki Thi', artist: 'Kumar Sanu & Alka Yagnik', year: '1992' },
    { id: 'nG85YFR3o6U', title: 'Tune Dil Mera Toda', artist: 'Kumar Sanu', year: '1993' },
    { id: 'tPNwGuu_rQ4', title: 'Tumhein Apna Banane Ki Kasam', artist: 'Kumar Sanu & Anuradha Paudwal', year: '1991' },
    { id: 'BtdiNnrftYM', title: 'Chand Tare Phool', artist: 'Kumar Sanu', year: '2002' },
    { id: 'qGOTe3KmCdY', title: 'Kitna Haseen Chehra', artist: 'Kumar Sanu', year: '1994' },
    { id: 'Y-o8NQ8Y36A', title: 'Is Tarah Aashiqui Ka', artist: 'Kumar Sanu', year: '1994' },
    { id: 'htMvfOfixuM', title: 'Ek Ladki Ko Dekha', artist: 'Kumar Sanu', year: '1994' },
    { id: 'HoMSu1iw0Zw', title: 'Aitbaar Nahi Karna', artist: 'Abhijeet Bhattacharya', year: '2003' },
    { id: '9f6GhUb-WdM', title: 'Dil Cheer Ke Dekh', artist: 'Kumar Sanu', year: '1993' },
    { id: 'w89fWEelFns', title: 'Paas Woh Aane Lage', artist: 'Kumar Sanu & Alka Yagnik', year: '1994' },
    { id: 'fg9G1dacXjk', title: 'Chhupana Bhi Nahin Aata', artist: 'Vinod Rathod', year: '1993' },
    { id: 'WAgJ8KM5AVQ', title: 'Dekha Hai Pehli Baar', artist: 'Alka Yagnik & SPB', year: '1991' },
    { id: 'p1jhKCIoVjI', title: 'Tum Dil Ki Dhadkan Mein', artist: 'Abhijeet Bhattacharya', year: '2000' },
    { id: 'fBylcT-TWZw', title: 'Bas Ek Sanam Chahiye', artist: 'Kumar Sanu', year: '1990' },
    { id: 'dDR4oiyjUBA', title: 'Raah Mein Unse Mulaqat', artist: 'Kumar Sanu & Alka Yagnik', year: '1994' },
    { id: 'oEg_iXEWlt4', title: 'Tu Meri Zindagi Hai', artist: 'Kumar Sanu & Anuradha Paudwal', year: '1990' },
    { id: 'iCZfjggJg3M', title: 'Kyo Kisi Ko', artist: 'Udit Narayan', year: '2003' },
    { id: 'TRUuSFW80Rk', title: 'Kaash Kahin Aisa Hota', artist: 'Kumar Sanu', year: '1994' },
    { id: 'wYdXuNtJkPk', title: 'Jeeye To Jeeye Kaise', artist: 'Pankaj Udhas & Kumar Sanu', year: '1991' },
    { id: 'Mfeg92XPXik', title: 'Dil Deewana', artist: 'S. P. Balasubrahmanyam', year: '1989' },
    { id: 'XWKazQwFFdY', title: 'Tere Dard Se Dil Aabad Raha', artist: 'Kumar Sanu', year: '1992' },
    { id: '-pIMyf5dOnA', title: 'Aawara Hawa Ka Jhonka Hoon', artist: 'Altaf Raja', year: '1997' },
    { id: 'nNhv8A_rJTg', title: 'Oye Raju Pyar Na Kariyo', artist: 'Anand Raj Anand', year: '2000' },
    { id: 'lRBIcaSV-Ns', title: 'Tum To Thehre Pardesi', artist: 'Altaf Raja', year: '1997' },
    { id: 'G7AdjVDBLO8', title: 'Achha Sila Diya Toone Mere Pyar Ka', artist: 'Sonu Nigam', year: '1995' },
    { id: 'TgHYW8ubFko', title: 'Tere Dard Se Dil', artist: 'Kumar Sanu', year: '1992' },
    { id: 'uIOrAkrjwp4', title: 'Hum Yaar Hai Tumhare', artist: 'Udit Narayan & Alka Yagnik', year: '2002' },
    { id: 'i1IsLVz6T9Q', title: 'Teri Umeed Tera Intezar', artist: 'Kumar Sanu & Sadhana Sargam', year: '1992' },
    { id: '3NWMK2MRqIk', title: 'Tumsa Koi Pyaara', artist: 'Kumar Sanu & Alka Yagnik', year: '1994' },
    { id: 'd3lZvNexPL0', title: 'Bahut Pyar Karte Hain', artist: 'SPB & Anuradha Paudwal', year: '1991' },
    { id: 'OgocnLh9P1M', title: 'Aankh Hai Bhari Bhari', artist: 'Kumar Sanu', year: '2002' },
    { id: 'oFxbBeYhLqM', title: 'Saaton Janam Main Tere', artist: 'Kumar Sanu', year: '1994' },
    { id: '9v2bq2JHt4I', title: 'Chehra Kya Dekhte Ho', artist: 'Kumar Sanu & Asha Bhosle', year: '1996' },
    { id: 'lFdSi01tpYM', title: 'Sochenge Tumhe Pyar', artist: 'Kumar Sanu', year: '1992' },
    { id: '_dUAVM5ERXA', title: 'Pehli Baar Mile Hain', artist: 'SPB', year: '1991' },
    { id: '6Na7GSV9bVY', title: 'Chura Ke Dil Mera', artist: 'Kumar Sanu & Alka Yagnik', year: '1994' },
    { id: 'Gg9ZUppafLo', title: 'Too Shayar Hai Main Teri Shayari', artist: 'Alka Yagnik', year: '1991' },
    { id: 'BaAoZA0fup0', title: 'Dil Ka Aalam', artist: 'Kumar Sanu', year: '1990' },
    { id: 'CTNgz5gb3D8', title: 'Tu Pyar Hai Kisi Aur Ka', artist: 'Babla Mehta & Anuradha Paudwal', year: '1991' },
    { id: 'nRJ8vHpi6_g', title: 'Tum Dil Ki Dhadkan Mein', artist: 'Kumar Sanu', year: '2000' },
    { id: 'Zi9UBJQMz3I', title: 'Kya Karte They Sajna', artist: 'Anuradha Paudwal & Udit Narayan', year: '1991' },
    { id: 'CTuvMubzXpU', title: 'Jeeta Tha Jiske Liye', artist: 'Kumar Sanu & Alka Yagnik', year: '1994' },
    { id: '5y_TCKNzAMI', title: 'Ghar Se Nikalte Hi', artist: 'Udit Narayan', year: '1996' },
    { id: 'cGKBs7rokos', title: 'Tujhko Na Dekhu Toh', artist: 'Udit Narayan & Sunidhi Chauhan', year: '1999' },
    { id: '2OsyNo53MzU', title: 'Dulhe Ka Sehra Suhana', artist: 'Nusrat Fateh Ali Khan', year: '2000' },
    { id: '4ImdbyqnH8w', title: 'Hum Pyaar Hai Tumhare', artist: 'Kumar Sanu & Alka Yagnik', year: '2002' },
    { id: 'GxaTSDnI71w', title: 'Aaye Ho Meri Zindagi Mein', artist: 'Udit Narayan', year: '1996' },
    { id: '-N-k56i7M2k', title: 'Maine Pyaar Tumhi Se Kiya Hai', artist: 'Kumar Sanu & Anuradha Paudwal', year: '1991' },
    { id: 'xKx_80QM2LU', title: 'Sab Kuchh Bhula Diya', artist: 'Sonu Nigam & Sapna Awasthi', year: '2002' },
    { id: 'RjJxWRFfG3s', title: 'Nahin Yeh Ho Nahin Sakta', artist: 'Kumar Sanu & Sadhana Sargam', year: '1995' },
    { id: 'cBGDDBHN22U', title: 'Pehli Pehli Baar Mohabbat Ki Hai', artist: 'Kumar Sanu & Alka Yagnik', year: '1999' },
    { id: 'zuPoUsdXrqM', title: 'Dheere Dheere Pyar Ko Badhana Hai', artist: 'Kumar Sanu & Alka Yagnik', year: '1991' },
    { id: 'N0jnLZxYwYc', title: 'Mujhse Mohabbat Ka Izhaar', artist: 'Kumar Sanu & Alka Yagnik', year: '1993' },
    { id: 'wV8njoRVefQ', title: 'Kitna Pyaara Tujhe Rabne Banaya', artist: 'Udit Narayan & Alka Yagnik', year: '1996' },
    { id: 'rMbQufI9xQw', title: 'Premi Aashiq Aawaara', artist: 'Kumar Sanu', year: '1991' },
    { id: 'rXHY4Cv9cA8', title: 'Ab Tere Bin Jee Lenge Hum', artist: 'Kumar Sanu', year: '1990' },
    { id: 'bga_0ziOOfQ', title: 'Woh Meri Neend Mera Chain', artist: 'Sadhana Sargam', year: '1993' },
    { id: 'QjqKXFGM3eI', title: 'Chori Chori Dil Tera', artist: 'Kumar Sanu & Sujatha', year: '1998' },
    { id: '526hvVlBP1U', title: 'Tumse Milna', artist: 'Udit Narayan & Alka Yagnik', year: '2003' },
    { id: '5dWbn_qER3s', title: 'Tere Dar Par Sanam', artist: 'Kumar Sanu', year: '1993' },
  ],

  // ── CHENNAI ── Curated Tamil Hits Pool (46 verified embeddable tracks)
  chennai: [
    { id: 'RVcEfPXPOxA', title: 'Kadhal Neethana', artist: 'Unni Krishnan' },
    { id: 'NBDLr7I8eZM', title: 'Minnalai Pidithu - Video Song', artist: 'Star Music Spot' },
    { id: '8gWstqAJOdc', title: 'Kaadhal Kaditham Official Video', artist: 'New Music India' },
    { id: 'pkf1XeIiacQ', title: 'Paasamulla Paandiyare', artist: 'Ilaiyaraaja' },
    { id: 'TF5TT6F5UuY', title: 'Kanmani Anbodu Kadhalan', artist: 'Release' },
    { id: 'Wr6EtdD_vco', title: 'Maalai Yen Vedhanai', artist: 'Ilaiyaraaja' },
    { id: 'HJAU_csxBVI', title: 'Oh Nenje Nenje', artist: 'Deva' },
    { id: 'c4T-fFUXznA', title: 'Ennavale Adi Ennavale', artist: 'Unni Krishnan' },
    { id: 'qYZbrooeP48', title: 'Nee Kaatru Naan Maram', artist: 'Release' },
    { id: 'z_3L58ny9Ow', title: 'Vanna Nilave - HQ Audio Song', artist: 'Tamil Music Video' },
    { id: 'z53_3ryHBHM', title: 'April Maathathil', artist: 'Deva' },
    { id: 'wqUy5UVO5vs', title: 'Pudhiya Mugam - July Matham Lyric', artist: 'SonyMusicSouthVEVO' },
    { id: 'njTC4d0vSXY', title: 'Thalapathi Movie Songs', artist: 'Lahari' },
    { id: 'Qmt-rk7_bK4', title: 'Rosappu Chinna Rosappu', artist: 'Hariharan' },
    { id: 'WfwCtR1iLFw', title: 'Kannalanae Full Video Song', artist: 'Music Master | Tamil Songs' },
    { id: 'dp0tSJW_xUs', title: 'Chinna Chinna Asai Video Song', artist: 'Lahari' },
    { id: 'qX-aKTpRJ4s', title: 'உன்னைப் பார்த்த பின்பு நான் நானாக இல்லையே  பாடல்', artist: '4k Classic Movies & Song' },
    { id: 'Fuvp2-gyYe8', title: 'Azagiya Laila', artist: 'Mano' },
    { id: 'DuZ_nWUQkO0', title: 'Nan Dum Adikura HD', artist: 'Master Music Collection Songs' },
    { id: 'xm7f0xrnTz4', title: 'Irupathu Kodi - Video Song', artist: 'Star Music India' },
    { id: 'mmc-FNhZwQU', title: 'Pudhu Vellai Mazhai', artist: 'Unnimenon' },
    { id: 'UWaotTkNCPk', title: 'Nenjinile Nenjinile Video Song', artist: 'Track Musics India' },
    { id: 'BJsVMh64AHo', title: 'Sollamale', artist: 'Release' },
    { id: '4kTKfUuNKbQ', title: 'Senthamizh Nattu Thamizhachiea', artist: 'Vairamuthu' },
    { id: 'TtvriQWof1o', title: 'Rakkamma Full Video Song with Lyric', artist: 'Lahari' },
    { id: 'y77F4NZBaHI', title: 'Nee Kaatru Naan Maram', artist: 'Vidyasagar' },
    { id: '5Fer1pCxXPA', title: 'Mukkala Mukkabala Lyrical', artist: 'Aditya' },
    { id: 'pLttfCzNdg8', title: 'Thullatha Manamum Thullum Tamil Movie', artist: 'Star Music India' },
    { id: '-YLjQzfNI4w', title: 'Andamaina Premarani Lyrical', artist: 'Aditya' },
    { id: 'zFK9eofeNj0', title: 'Pettai Rap', artist: 'Suresh Peters' },
    { id: 'Z2b2STaRSDI', title: 'Annamalai Video Songs', artist: 'Lahari' },
    { id: '5UtyrkoKnIw', title: 'Ennavale Ennavale - Audio Song', artist: 'Star Music India' },
    { id: 'P9E5IxNkIHk', title: 'Urvashi Uravashi', artist: 'A. R. Rahman' },
    { id: 'Zwn179txFbQ', title: 'September Madham with Lyrics', artist: 'Saregama' },
    { id: 'YMpdgQXfymk', title: 'Poongatrile 4K lyrical Song', artist: 'Track Musics India' },
    { id: 'gRjKULlhot4', title: 'Karna - Malare Mounama Video', artist: 'Sony Music South' },
    { id: 'GllWQCXur4Y', title: 'Engengey', artist: 'Deva' },
    { id: '3CMr54Jm0Io', title: 'Aval Varuvala', artist: 'Deva' },
    { id: 'nHcRZpnSFec', title: 'Azagaana Manjapura Lyrical Song', artist: 'Saregama' },
    { id: 'N_jkpSsF54A', title: 'Sotta Sotta Official Video', artist: 'New Music India' },
    { id: 'INICVDmDN8c', title: 'Ennai Thalatta Varuvala', artist: 'Hariharan' },
    { id: 'KWlrs2Uhxx4', title: 'Oh Sona', artist: 'Deva' },
    { id: 'fh5XrLxKBXI', title: 'Chakku Chakku Vaththikuchi', artist: 'Saregama' },
    { id: 'bsHAHP9LxuY', title: 'Thendral Vanthu Theendumbothu', artist: 'Ilaiyaraaja' },
    { id: 'KxjiPgpVkqc', title: 'Anbay', artist: 'A. R. Rahman' },
    { id: 'u_qJ9I0_KaM', title: 'Marugo Marugo Lyric Video', artist: 'Ilaiyaraaja' },
  ],

  // ── KOLKATA ── Verified Playable Pool (40 tracks)
  kolkata: [
    { id: 'D1T1ykAIsmI', title: 'Janmadin', artist: 'Kishore Kumar' },
    { id: 'ZTADf7YxB6A', title: 'Ogo Nirupama', artist: 'Kishore Kumar' },
    { id: 'yfU7MFjeJr8', title: 'Akash Keno Daake', artist: 'Kishore Kumar' },
    { id: 'EQBo0OVSGXQ', title: 'Nayan Sarasi Keno Bhoreche Jaale', artist: 'Kishore Kumar' },
    { id: 'dRP9WX68-BA', title: 'Opare Thakbo Ami', artist: 'Kishore Kumar' },
    { id: '8mEQoJ_tfoE', title: 'Ami Je Ke Tomar', artist: 'Kishore Kumar' },
    { id: 'TiMwYJnhQxU', title: 'E Ki Holo', artist: 'Kishore Kumar' },
    { id: 'VCebf0pJfcI', title: 'Ami Je Ke Tomar (Solo)', artist: 'Kishore Kumar' },
    { id: 'TMD6tSpqck0', title: 'Shing Nei Tobu Naam Tar Singha', artist: 'Kishore Kumar' },
    { id: 't79CKAMVLuA', title: 'Gopone Gopone Koto Kotha', artist: 'Kishore Kumar' },
    { id: '57XEh9wh9bE', title: 'Kichhu Katha Chhilo Chokhe', artist: 'Kishore Kumar' },
    { id: '2TtQMeZDYkY', title: 'Chedona Chedona Haat', artist: 'Kishore Kumar' },
    { id: 'AYRTuS1z3vo', title: 'Sei Raate Raat Chhilo Purnima', artist: 'Kishore Kumar' },
    { id: 'Prgm9TioYQY', title: 'Kishore Kumar Bangla classics', artist: 'Kishore Kumar' },
    { id: 'BnEb1Yb1_AI', title: 'Ek Din Pakhi Ure Jabe', artist: 'Kishore Kumar' },
    { id: '1PKRehP3SqY', title: 'Charulata Movie Songs', artist: 'Kishore Kumar' },
    { id: '6HwQl-IK7vg', title: 'Ek Din Pakhi Ure Jabe', artist: 'Kishore Kumar' },
    { id: 'x2zrQHQwj3U', title: 'Aar Kato Byatha Ami Pabo with lyrics', artist: 'Kishore Kumar' },
    { id: 'FTNflkI0Y3Y', title: 'Memorable Hits Of Kishore Kumar', artist: 'Kishore Kumar' },
    { id: 'rsJqXh2OtNc', title: 'All Time Greats-Kishore Kumar', artist: 'Kishore Kumar' },
    { id: 'FmTBAJQO620', title: 'Cheyechhi Jare Ami', artist: 'Kishore Kumar' },
    { id: 'j50_hgfkK0Q', title: 'Evergreen Kishore Kumar', artist: 'Kishore Kumar' },
    { id: 'GZU-o6D3RIo', title: 'Kishore Kumar Gaan', artist: 'Kishore Kumar' },
    { id: '_T4AylDyBHY', title: 'Aaj Hridaye Bhalobese', artist: 'Kishore Kumar' },
    { id: '1HI4nE4Xcug', title: 'Anek Jamano Byatha', artist: 'Kishore Kumar' },
    { id: 'xRoD_ylr4M0', title: 'নয়ন সরসী কেনো ভরেছে জলে', artist: 'Kishore Kumar' },
    { id: 'XZ_J8yqlrc0', title: 'Bidhir Bandhan Katbe Tumi with Lyrics', artist: 'Kishore Kumar' },
    { id: 'MyB4VDhfB8U', title: 'Carvaan Classic Radio Show', artist: 'Kishore Kumar' },
    { id: 'OO-a0MrDBPY', title: 'Prem Baro Madhur', artist: 'Kishore Kumar' },
    { id: 'KigjSXLBorc', title: 'Asha Chhilo Bhalobasa Chhilo', artist: 'Kishore Kumar' },
    { id: '_XiORSNyF74', title: 'Bengali Songs by Kishore Kumar', artist: 'Kishore Kumar' },
    { id: 'qsYC7klJrnA', title: 'Aaj Ei Dintake', artist: 'Kishore Kumar' },
    { id: 'NouFV7XRvd4', title: 'Top 5 Songs of kishore kumar', artist: 'Kishore Kumar' },
    { id: 'pnA8Ko268kM', title: 'ঝলমল ঝলমল তাঁতের শাড়ি', artist: 'Kishore Kumar' },
    { id: 'mZMWKYZnD74', title: 'Ei To Hethay Kunja Chhayay', artist: 'Kishore Kumar' },
    { id: 'bVaaOPAHfW8', title: 'Amar Swapna Tumi Ogo', artist: 'Kishore Kumar' },
    { id: 'xtE2kRuee3g', title: 'Tare Ami Chokhe Dekhini', artist: 'Kishore Kumar' },
    { id: 'htbiDAEuk_A', title: 'Amar Moner Ei Mayurmahale With Lyrics', artist: 'Kishore Kumar' },
    { id: 'vYmzNTqJVfs', title: 'Kishore Bangla Lofi Hits', artist: 'Kishore Kumar' },
    { id: 'dTZWqTrKYHQ', title: 'Haowa Megh Saraye Phul Jharaye', artist: 'Kishore Kumar' },
  ],

};

// Fisher-Yates Shuffle algorithm
export function shuffleArray<T>(array: T[]): T[] {
  const copy = [...array];
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

// Generate randomized shuffles for all region locations on site load/session start
export function createShuffledPlaylists(): Record<Region, Track[]> {
  return {
    mumbai: shuffleArray(playlist.mumbai),
    delhi: shuffleArray(playlist.delhi),
    chennai: shuffleArray(playlist.chennai),
    kolkata: shuffleArray(playlist.kolkata),
  };
}

// Helper to get next track index (loops)
export function getNextIndex(current: number, total: number): number {
  return (current + 1) % total;
}

export function getPrevIndex(current: number, total: number): number {
  return (current - 1 + total) % total;
}

// ── BARBER'S PICK — One personally curated track per region ─────────────────
export const BARBERS_PICK: Record<Region, string> = {
  mumbai: '8VgEQ1CqYTw',   // Ek Ladki Ko Dekha
  delhi: 'otQmzlm-s7Q',    // Main Duniya Bhula Doonga
  chennai: 'RVcEfPXPOxA',  // Vaathi Coming
  kolkata: 'D1T1ykAIsmI',  // Janmadin
};
